Issue #63 Create Practice Area Model
hackforla/peopledepot pull request #156
Opened 2023-05-03 20:37 UTC by ethanstrominger

Issue #63 Create Practice Area Model

2023-05-04 21:59 UTC, fyliu requested changes
Looks good. Admin site and API endpoint works.
I think you're going to push the lint fixes.
Looks like there's a name mix up with the tests.

2023-05-17 16:44 UTC, ethanstrominger commented on app/core/tests/test_models.py
> +    assert str(recurring_event) == "Test Practice Area"
How do I use a fixture here?  I did not see fixtures in other places.  Or did you just mean I should use practice_area instead of recurring_event?

2023-05-17 16:45 UTC, ethanstrominger commented on app/core/tests/test_api.py
> +PRACTICE_AREA_URL = reverse("practice-area--list")
Fixed

2023-05-30 18:35 UTC, fyliu requested changes
Just a couple more things.

2023-05-30 18:35 UTC, fyliu commented on app/core/admin.py
> +class PracticeArea(admin.ModelAdmin):
Just a nitpick. This should be PracticeAreaAdmin, just to follow the convention.

There are other classes in this file that missed this. I can correct all of them separately too.

2023-05-30 18:35 UTC, fyliu commented on app/core/api/views.py
> +class PracticeAreaViewSet(viewsets.ModelViewSet):
This is missing the OpenAPI doc strings for the endpoint.
The @extend_schema_view block

2023-05-31 18:26 UTC, fyliu approved these changes
Looks good!

2023-05-31 18:28 UTC, merged

2023-10-02 21:28 UTC, ExperimentsInHonesty commented
Fixes #63