Change all instances of recurring_event in the code to event
hackforla/peopledepot pull request #209
Opened 2023-09-28 09:39 UTC by anandramakris

All instances of recurring_event in the code have been changed to event. Works correctly in Django on Google Chrome, with the computer running Windows 10.

Documentation will need to be changed as the create table tutorial focuses on the recurring-event table.

2023-10-01 15:01 UTC, AzaniaBG commented on app/core/api/serializers.py
>      """Used to retrieve recurring_event info"""
The doc string still refers to "recurring_event"

2023-10-01 15:33 UTC, AzaniaBG reviewed
@anandramakris, nice work on this. It appears all instances of recurring_event have been changed to event. Also, thank you for pointing out that documentation will need to be changed. Specifically, the [add-models-and api-endpoints.md](https://github.com/hackforla/peopledepot/blob/main/docs/how-to/add-model-and-api-endpoints.md#add-the-model-in-django) still references the "recurring_event" model.

I left an inline comment where the doc string still refers to "recurring_event" (in `serializers.py`). Also, when I navigate to localhost:8000/admin/core/event, I see an error:"core_event" does not exist. I'm not sure if migrations need to be rolled back and run again, because I'm seeing an exception/error "raise InconsistentMigrationHistory" when I run `./scripts/buildrun.sh.` 

@fyliu: I believe these are the changes that need to be made:
1. change the doc string to reference "event"
2. fix the inconsistent migration history
Also, in the future, I suggest using a branch name that includes the issue number, instead of using the `main` branch.

2023-10-01 17:43 UTC, anandramakris commented
I didn't get that error at all, thanks for noticing on your end.

2023-10-01 17:53 UTC, anandramakris commented
Tested right now on my end if the migration error still occurs and it just says "No migrations to apply."

2023-10-12 22:40 UTC, fyliu requested changes
Thanks for working on this.

I see that you re-did the 0004_recurringevent.py migration into 0004_event.py migration. You should actually just leave the old migration files alone and let django generate a new migration file to do the deletions. You probably weighed the choices and it felt cleaner to do this. But rewriting migration files will break the database for the people have have the project deployed locally, where their databases were built using the old migration files. We don't have a publicly-deployed instance to worry about for now, but we should always add to migrations so that running instance can update to the new database schema.

Before public deployment, we will flatten all the existing migration file into one to reduce the number of them and to get rid of design redo changes like this one.

2023-10-18 14:46 UTC, fyliu commented
@anandramakris yes, exactly. We should let it generate a new migration for the change.

2023-10-25 13:10 UTC, AzaniaBG commented
@fyliu @anandramakris ~ I might be missing something, but when I click on the GH email link for the latest commit, I see the following message: "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."
<img width="861" alt="Screenshot 2023-10-25 at 6 10 16 AM" src="https://github.com/hackforla/peopledepot/assets/52610573/93249223-f75f-457b-8fdd-7f40373481bd">

2023-10-25 13:38 UTC, AzaniaBG commented
@anandramakris @fyliu ~ I requested changes. Anand, can you edit your commit message to add the changes you made using this template[this pull request template](https://github.com/hackforla/peopledepot/compare/29b4eddafdf911a0b2157563c26d270073c22cfa..b8a3766c61ca106e66c3d18ab6e995caa168dd84#diff-b2496e80299b8c3150b1944450bd81c622e04e13d15c411d291db0927d75fd6b)?

Also, the force commit has caused an issue that makes it difficult to find the commit on the branch. For example, I see a message that the commit does not belong to a branch on the repo when clicking the GH email commit link to get to your   latest commit. Also, when I navigate to issue #209, I see a message that the commits can't be found (see screenshots below). 

<img width="836" alt="Screenshot 2023-10-25 at 6 34 26 AM" src="https://github.com/hackforla/peopledepot/assets/52610573/0fea2c1a-3dd6-482e-a489-70be1f0daeb0">

![Screenshot 2023-10-25 at 6 31 16 AM](https://github.com/hackforla/peopledepot/assets/52610573/aff1f9bf-7665-4ae6-85d0-4512c5cbd72a)

2023-10-25 21:37 UTC, fyliu requested changes
Looks good. The only thing is probably changing the short message of the commit to something other than "Fixed migration files". Something like "Rename recurring_event to event" is better. `git commit --amend` should let you edit the message. Then I guess you'll have to force push

And the PR template @AzaniaBG talked about if you want to copy it from the templates directory and replace the PR description with it.

What I did to test

- I deleted my data volume, built the previous commit, updated to your commit, and ran migrate. It applied the new 0018 migration without errors.

    ```bash
    docker-compose down -v

    # reset to previous commit

    ./scripts/buildrun.sh

    # reset to PR commit

    ./scripts/migrate.sh
    ```

- admin site and api look okay

- Grepping for "recurring" didn't show any more that need changing

    ```bash
    grep -nirs -I --exclude-dir=".git" "recurring" .
    ```

2023-10-26 17:51 UTC, anandramakris commented
Have changed the commit message.

2023-10-27 00:07 UTC, fyliu approved these changes
Looks good. Thanks for making the changes.

2023-10-27 00:08 UTC, merged