Create prod Dockerimage from alpine base image
hackforla/peopledepot pull request #222
Opened 2023-10-30 02:28 UTC by alexlaw528

Fixes #177 

### What changes did you make?
- Added a production Docker image using alpine as base-image.

### Why did you make the changes (we will use this info to test)?
- Current Docker image is meant for development. It utilizes a larger base-image and contains dependencies unused in production.
- Reduced image size from 1.26 GB to 392.06 MB

### Deploy prod environment locally
- Run following commands from` /peopledepot` root directory:

- Build production image as "alpine-pd"
`docker build -t alpine-pd -f ./app/prod/Dockerfile ./app/prod`

- Start up production services 
`docker-compose -f docker-compose.prod.yml up`

2023-10-31 22:18 UTC, fyliu commented
@alexlaw528 I think the "alpine" is usually part of the image tags. Like `-t pd:latest-alpine`

I'm not sure if there's a best practice for managing dev and prod dockerfiles. I see some people do Dockerfile.prod, or use the same Dockerfile for both with conditionals. I guess putting it in a directory is as good as any. We can think about this later.

We should also do multistage build to maybe avoid part of the 211MB that system dependencies take up. This is just a note for a later issue.

2023-11-02 21:59 UTC, fyliu requested changes
Thanks for working on this. Please excuse some of the comments that read more like I'm not sure if it needs a change. I think there's some miscommunication in the issue. The issue was intended to convert the development Dockerfile to use alpine and apk. It's okay to do it for production too. I see you made copies of some files and removed the development dependencies. It's just that it's missing elements that I would consider to be needed for production, so I'm not sure if I should ask for them since they're not in the issue.

Or would it be okay if you just make the change to the development setup and then do the same for production? I'm not sure what the best way to do this is.

2023-11-02 21:59 UTC, fyliu commented on app/prod/requirements.txt
> +black~=22.3.0
I would remove black, drf-spectacular, pydot, and maybe django-linear-migrations from the production build. I don't think there's any use for them outside development.

2023-11-02 21:59 UTC, fyliu commented on docker-compose.prod.yml
> +      - ./.env.dev
Maybe have a separate .env or .env.prod file for production

2023-11-02 21:59 UTC, fyliu commented on docker-compose.prod.yml
> +    container_name: people_depot_db
Setting the container name might not be a good idea. I'll have to look up the reasoning for this again.

2023-11-02 21:59 UTC, fyliu commented on docker-compose.prod.yml
> +    container_name: people_depot_db
Oh yeah, the container_name allows you to refer to it by name in a `docker` command. If you intend to refer to it using docker-compose, like `docker-compose run db...` then you only need to use the service name. Setting the container name also restricts docker-compose from generating multiple instances of it. I'm not sure if there's an advantage to that or not. So the reasoning for not setting it is really that it's not very useful.

2023-11-02 21:59 UTC, fyliu commented on docker-compose.yml
> +    container_name: people_depot_dev
Same reasoning as above for not setting the container name. We're mainly referring to containers using `docker-compose`.

2023-11-02 21:59 UTC, fyliu commented on app/prod/Dockerfile
This is probably fine as a conversion from apt to apk. It's missing some production things that we can add in other issues. Multi-stage build, --no-compile flag, maybe apk cache cleanup.

2024-05-03 00:25 UTC, ExperimentsInHonesty commented
- We are closing this and it's being replaced by #275

2024-05-03 00:25 UTC, closed without merging