Changes for kb
hackforla/peopledepot pull request #228
Opened 2023-12-05 18:34 UTC by ethanstrominger

Fixes #replace_this_text_with_the_issue_number

### What changes did you make?

-
-
-

### Why did you make the changes (we will use this info to test)?

-
-
-

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2023-12-05 18:34 UTC, ethanstrominger commented on app/core/api/serializers.py
>          model = ProgramArea
Go back to uuid

2023-12-05 18:35 UTC, ethanstrominger commented on app/core/api/urls.py
> +    path('home/', TemplateView.as_view(template_name='common/home.html'), name='home'),
fix this one

2023-12-27 21:58 UTC, fyliu requested changes
Maybe it's too early for me to review this since several things aren't complete yet.

Looks like there's a lot of directions to the changes. Some of them might be better split into their own PRs to review separately.

1. cognito auth client in the backend
    - missing instructions on how to use it. What url to use. Needing to create the client id in AWS and put it in the .env file.
1. things not needed
    - changing model id between int and uuid (it's also causing existing tests to fail)
    - changing the .env file name
    - envsettings.sh file
1. shouldn't be needed
    - API for peopledepot clients to create new peopledepot users
    - default assigning staff to new users allows all users to use the admin site
1. scripts and instructions for running the backend without docker

2023-12-28 03:05 UTC, fyliu commented on app/templates/account/login.html
I think it's `accounts/login.html`. Accounts with an s at the end.

2024-01-26 01:50 UTC, closed without merging