Convert doc pages to mkdocs
hackforla/peopledepot pull request #244
Opened 2024-01-18 23:11 UTC by fyliu

Fixes #167

### What changes did you make?

- 
-
-

### Why did you make the changes (we will use this info to test)?

-
-
-

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2024-05-24 02:05 UTC, fyliu commented
I added examples to the documentation for mkdocs and the description for this PR. This is now ready for review.

2024-06-07 07:25 UTC, freaky4wrld requested changes
@fyliu thanks for making such a vast and detailed documentation..... reviewing it was nice, I came to know across the `Mkdocs` it's useful and UI-friendly.

Here are my observations:
- In the `Contributing.md` after `line 433` you somehow copied the whole document again and it's showing again in the `mkdocs site`. I guess we should remove that duplicity. Below is the reference for you:
<details>
<img width="1440" alt="image" src="https://github.com/hackforla/peopledepot/assets/134206855/6b459b4a-e457-4076-9942-d873ae343a9d">
</details>

- The `add-model-and-api-endpoint.md` everything seems fine, I like the feature where a detailed description is given in the code-block

- The `mkdocs.md` is great as well and you tried to added most of the things.

Making the suggested changes will make it good to go. Thanks for your contribution really appreciate your effort to contribute your knowledge in most laymen terms.

2024-06-08 01:35 UTC, fyliu commented
@freaky4wrld Thank you so much for catching this duplication. It looks like the page is duplicated even though the page contents on the right doesn't show it.

I guess the duplication has been there for a couple months already. I used `git blame` to see when it last changed.

```
❯ git blame CONTRIBUTING.md -L 433,435
2 months ago    Ethan-Stroming  ec465270│ 433│                                                                        
                                        │ 434│ # Contributing                                                         
                                        │ 435│                                                                        

```

I'll make a ER to resolve any differences within that file before applying the changes from this PR.

2024-06-08 23:45 UTC, fyliu commented on CONTRIBUTING.md
This will be resolved once the PR #301 is merged and these changes are rebased.

2024-06-08 23:45 UTC, fyliu commented on CONTRIBUTING.md
> +!!! note "If you are using Visual studios code you can use the Git graphical user interface to stage your changes. For instructions check out the [Git GUI page in the website Wiki](<https://github.co
This will be resolved once the PR #301 is merged and these changes are rebased.

2024-06-08 23:45 UTC, fyliu commented on CONTRIBUTING.md
> -
This will be resolved once the PR #301 is merged and these changes are rebased.

2024-08-02 19:03 UTC, fyliu commented
Eliminated duplicate content in CONTRIBUTING.md and updated screenshot.

Also fixed some other problems and added line numbers to code listings.

This is ready for review again.

2024-08-13 21:38 UTC, fyliu commented
@freaky4wrld can you look at this PR again? Sorry I force pushed. I should have added new fix commits and then do cleanup after the PR is approved.

2024-08-15 06:16 UTC, freaky4wrld approved these changes
@fyliu thanks for making the changes and contributing in creating the documentation visually appealing and easy to understand
- the UI is great 
- there's no duplication this time

PR approved!!

2024-08-15 21:17 UTC, merged