Add sdg seed data
hackforla/peopledepot pull request #256
Opened 2024-02-21 08:35 UTC by freaky4wrld

Fixes #250 

### What changes did you make?

- Added json file for seed data
- Added the converted python file
- Added the migrations file to add seed data

### Why did you make the changes (we will use this info to test)?

- To add the seed data for sdg model
-
-

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2024-02-21 08:38 UTC, freaky4wrld commented
@fyliu I'm having trouble with the seed data as it is exceeding the flake8 199 character criteria, can you please provide the instruction

2024-02-21 22:17 UTC, fyliu commented
@freaky4wrld you can add `data/migrations` to the ignore list for flake8 in the pre-commit config. See `.pre-commit-config.yaml` in the project root for an example of multiple excludes and also the hook to modify.

2024-02-22 23:42 UTC, fyliu requested changes
Looks good. Just a small thing I saw that needs fixing.

I saw that the coverage report says there's many lines in `0003_sdg_seed.py` not covered. But it didn't complain about `0002_practicearea_seed.py`. So I compared the files and found that the last line in `0003_...` isn't in the function to be called during a migration.

2024-02-22 23:42 UTC, fyliu commented on app/data/migrations/0003_sdg_seed.py
> +operations = [migrations.RunPython(run, migrations.RunPython.noop)]
This line should be part of `Migration`

2024-03-01 00:13 UTC, fyliu reviewed
Works well.

Maybe delte the `sdg_seed.py` since it's incorporated into the migration file.

2024-03-07 09:04 UTC, fyliu approved these changes
Looks good

2024-03-07 09:05 UTC, merged