Implement user_permissions model, api, and test
hackforla/peopledepot pull request #342
Opened 2024-07-01 22:52 UTC by ethanstrominger

Fixes #22

### What changes did you make?

- standard changes:
   - models.py
   - serializers.py
   - views.py
   - urls.py
   - admin.py
   - 00024_user_permissions_and_more.py
- constants.py: new file for holding constants for code for practice area admin and project lead.  This will be utilized more going forward.
- 0004_perimission_types_seed.py: populates permission type with project lead and practice area admin
- conftest.py.  Added fixtures:
  - created_superuser: creates a user that is a superuser for logging in.  In future changes, a non-super user without any other user permissions config will be able to access user permissions api.
  - created_user_permissions: creates two users, each with an associated user permission
- test_api
  - test get_user_permissions(created_superuser, created_user_permissions)
    - fixtures create necessary data
    - authenticate as the created superuser
    - call API to get user permissions
    - verify response status and count of response data

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2024-07-11 19:09 UTC, fyliu requested changes
Thanks for adding this and making the name more clear. I started the review but keep thinking I should look at it more. But here's what I have so far.

The migration files can be deleted and regenerated as one.

constants.py is only used in one file and seems unnecessary, but I assume it'll have more uses in future PRs.

Maybe add a model test for the str function for coverage to exercise the functionality.

2024-08-02 00:32 UTC, ExperimentsInHonesty commented on app/constants.py
> +global_admin = "Global Admin"
Here are the defined names on the PermissionType - Data spreadsheet
https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit?pli=1&gid=1448710921#gid=1448710921

adminGlobal
adminVrms
adminBrigade
adminProject
practiceLeadProject
memberProject
memberGeneral

2024-08-02 00:35 UTC, ExperimentsInHonesty submitted a review, later dismissed
Here are the defined names on the [PermissionType - Data spreadsheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit?pli=1&gid=1448710921#gid=1448710921) for the constants.py file

adminGlobal
adminVrms
adminBrigade
adminProject
practiceLeadProject
memberProject
memberGeneral

2024-09-05 09:07 UTC, fyliu commented on scripts/run.sh
These returns should really be exits. They're only behaving the same because I added the "set -e" guard to the top of the script (all the scripts).

If you removed the "set -euo pipefail" line and ran `./scripts/run.sh -f`, you'll see that it returns for the unrecognized option and then starts the docker containers anyway. It should really exit the entire script instead. Same withh `./scripts/run.sh -u` to print usage

Related change in another script: The returns in `start-local.sh` are okay since they're in the top level scope of the script. They end up behaving the same as exits (except that one return in the function scope that actually returns the value)

2024-09-08 08:34 UTC, fyliu requested changes
Can you discard the changes in `run.sh`? I commented on it but it wasn't a review so it didn't show requested changes.

2024-09-11 17:02 UTC, ethanstrominger commented on app/core/tests/test_api.py
> +    created_user_admin, created_user_permissions, auth_client
Modified

2024-09-11 21:15 UTC, fyliu requested changes
Thanks for making the changes. I haven't looked through the test yet, but I wanted to add what I found so far. Some of the comments don't require any change.

2024-09-11 21:15 UTC, fyliu commented on .pre-commit-config.yaml
This was was fine without the extra lines. They were removed a few commits ago in `main`

2024-09-11 21:15 UTC, fyliu commented on app/Dockerfile
> +  graphviz
Just commenting. @dmartin4820 had the better idea of 2.42.* version. But this is fine since we're about to move to alpine base.

2024-09-11 21:15 UTC, fyliu commented on app/core/api/serializers.py
> +        )
This is missing the read_only fields that the other models in the same file have. Actually, I'm not sure if they're settable from the API if you didn't declare them `read_only`.

2024-09-11 21:15 UTC, fyliu commented on app/core/models.py
> +    def __str__(self):
Just commenting. The way this is implemented is more like a `__repr__` function than a `__str__` function.

2024-09-19 21:59 UTC, fyliu approved these changes
Thanks for making the changes!

It's working well and all the tests pass!

2024-09-19 22:06 UTC, merged