Create Table: check_type #59
hackforla/peopledepot pull request #370
Opened 2024-08-21 04:06 UTC by dmartin4820

Fixes #59 

### What changes did you make?
- create a single model in Django (defining schema)
- add seed data
-write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of
- permissions on a project).
- write an API end point
- write API unit tests
- CONTRIBUTING.md: add relative path starting from ./app to step 2.3.2
- add-model-and-api-endpoints.md: add import model to views.py step 

### Why did you make the changes (we will use this info to test)?
- create table for check_type, completing one task as part of #25 
- updated docs to clarify and/or include steps I didn't find in the docs

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals change</summary>

- add-model-and-api-endpoints.md before:
![add_model_before](https://github.com/user-attachments/assets/2f13928d-a196-4903-ad92-198e8b3a4143)

- add-model-and-api-endpoints.md after:
![add_model_after](https://github.com/user-attachments/assets/a4c00205-ad26-4532-97a4-44ef33c3f2bd)

- CONTRIBUTING.md before:
![contributing_before](https://github.com/user-attachments/assets/0d401d81-cfbd-448d-bba9-a0ac85024894)

- CONTRIBUTING.md after:
![contributing_after](https://github.com/user-attachments/assets/5f7cc28c-8269-4280-9f7a-e38b37887280)

</details>

2024-08-22 22:20 UTC, fyliu requested changes
Thanks for working through the issue so quickly and fixing documentation problems!

Everything works great. I looked through the code, built it, ran it, checked migrations, the admin site, and the API endpoints.

I found only very minor things that doesn't affect the functionality. Can you please fix them? Thanks!

2024-08-26 00:26 UTC, dmartin4820 commented on app/core/admin.py
> +class CheckType(admin.ModelAdmin):
Changed in commit 89ce240

2024-08-26 00:26 UTC, dmartin4820 commented on docs/how-to/add-model-and-api-endpoints.md
> +1. Import the model
Changed in commit 89ce240

2024-08-26 00:53 UTC, fyliu approved these changes
Thank you for making the changes. Looks great!

2024-08-26 01:40 UTC, fyliu commented
@dmartin4820 I'm going to amend the later changes into the original commits before rebasing everything into main. I'm not sure if it's something you want to try doing yourself.

Also, the repo is set to delete the PR branch after merging. Since you're using the main branch of your from for the PR, I'm not sure if it's aware enough to not try to delete it. The delete is supposed to be reversible if it does happen.

2024-08-26 03:16 UTC, dmartin4820 commented
@fyliu sure, I'd be willing to try amending the commits. I'm familiar with soft resetting to a specific commit, the amending the unstaged changes to the last commit. After that, I'd need to force push to my fork

Not sure I know how to fixup the unstaged changes to specific commits, especially without a tool. But willing to learn more about it. 

I don't mind if it deletes the branch of the fork or whatever it ends up doing. I can create a new one.

2024-08-26 03:59 UTC, fyliu commented
Great. First, split the last commit into 2. You can soft reset 2 commits back so that all of the Fixup changes are there together. Actually, mixed reset might be better in this case. Mixed will unstage the committed changes while soft reset will keep them staged.

Then stage one of the changes like the app/core/admin.py change that could become the fixup for the "...register admin..." commit.
So have just that one change staged, then do 'git commit --fixup :/"register admin"' and it will create a fixup commit for the last commit in history with a short msg that matches that partial string. You can try doing the fixup now by running git commit -i --autosquash HEAD^10 . There's only 8-9 commits from HEAD back to "main", so 10 will go back enough to cover all of your changes. It'll open an editor with the rebase plan, and it'll move the fixup commit to right after the commit it's fixing up, with a fixup action in that line. Just close the editor and it will apply it correctly.

Then you can create the fixup commits for the other 2 things and apply them together. I just realized the remaining change is actually one thing, which is fixing the '...import model..." commit. I just wanted to say you can apply multiple fixups in the same autosquash commit.

After that, you should've combined all the fixes into the original commits and still have the exact same code as when the PR was approved. You can check using "git diff origin/main" I think. Then you can force push to replace what's in the PR.

In open source projects, some (many?) maintainers like to keep the main branch history clean and linear. So no fix commit for something earlier in the same PR and no merge commits. So rebase your commits to the latest main if main was changed before your PR.

They might do the cleanup themselves, ask contributors to do it, or have a merge team that's very adept at handling this. 

Thanks for wanting to try this. I wanted to give people this experience that they could encounter in the wild, but I also understand some people are at the stage where they're already learning several things at the same time and don't want another complication.

2024-08-26 04:07 UTC, fyliu commented
I can't remember the way to do it with a tool (lazygit) without using the computer, so I'll tell you later. That tool might do several git commands in the background for every action you tell it to take. You can do things like browse an old commit and tell it to commit part of it as a separate commit, splitting it into 2 at that point in history, with all the later commits after them.

2024-08-26 05:06 UTC, fyliu commented
## lazygit instructions

I did 2 things:

1. moved the pre-commit commit to before the "docs(add-model)" commit and applied it as a fixup.
1. split the last commit into 2 and moved and applied them to the correct commits in history.

### move and apply fixup

1. assume you're running `lazygit` and on the correct branch
1. focus on the commit panel by pressing "4"
1. move focus to the "pre-commit" line by pressing "j" and "k" to move the cursor down and up
1. move the commit down a position by pressing "ctrl-j"
1. apply the fixup by pressing "f" and "enter"

### split a commit into 2

1. assume you're running `lazygit` and on the correct branch
1. focus on the commit panel by pressing "4"
1. move focus to the commit you want to split by pressing "j" and "k" to move down and up. in this case, the top commit is where we want to be
1. explore the commit by pressing "enter"
1. stage the `admin.py` file by focusing on it and pressing "space"
1. call up the patch menu by pressing "ctrl-p"
1. select "Move patch into new commit" or press "n"
1. enter a new commit message like "fix admin class name" and press "enter"
1. the operation may take a number of seconds.

### move and apply fixup

same steps as above with the 2 newly split commits

2024-08-26 05:11 UTC, dmartin4820 commented
I'll give it a try. Definitely not opposed to learning more about Git

2024-08-26 06:59 UTC, dmartin4820 commented
So I did the fixups using lazygit. It was easier that way. It got rid of the "pre-commit" commit and fixedup the commits with the changes you suggest to the admin class name and docs.

2024-08-26 17:42 UTC, merged

2024-08-26 17:44 UTC, fyliu commented
@dmartin4820 looks great. Thanks!