Create table user status type 35
hackforla/peopledepot pull request #427
Opened 2024-10-28 19:00 UTC by del9ra

Fixes #35

### What changes did you make?

- created a model
- added seed data
- tested API endpoints and model

### Why did you make the changes (we will use this info to test)?
- to update a shared data store across hackforla.org, vrms, civictechjobs, and tables project

2024-10-29 02:32 UTC, dmartin4820 requested changes
Left some minor comments. I switched to your branch in my local peopledepot git area, and I ran 

```
1. ./scripts/buildrun.sh
2. ./scripts/test.sh
```

without issue.

Other than the few comments, it looks good to me 👍 .

2024-10-29 02:32 UTC, dmartin4820 commented on app/core/models.py
> +class UserStatusType(AbstractBaseModel):
Now that this model is going to be implemented, we should uncomment the one-to-many relationship [here](https://github.com/hackforla/peopledepot/blob/53b4a22507d040a9af5cc45a378b48afb01d8e79/app/core/models.py#L77), according to the tool tip under [here](https://github.com/hackforla/peopledepot/blob/53b4a22507d040a9af5cc45a378b48afb01d8e79/app/core/models.py#L77).

2024-10-31 05:36 UTC, fyliu requested changes
Great work!
I just have a couple of small things.

2024-11-04 02:53 UTC, dmartin4820 approved these changes
No other changes from me. Tested buildrun and test scripts with no issues as well. Good work.

2024-11-05 23:02 UTC, fyliu approved these changes
This looks great! Thank you for adding the user status type model!

2024-11-11 17:50 UTC, ethanstrominger approved these changes

2024-11-13 20:57 UTC, fyliu commented
I decided to squash the commits before merging because there's migrations that's replaced in later commits. Squashing them removes those intermediate files from history so that rolling forward from any past commit would work.

2024-11-13 20:57 UTC, merged