Create table project status 46
hackforla/peopledepot pull request #449
Opened 2024-11-21 06:14 UTC by dmartin4820

Fixes #46

### What changes did you make?

- created project_status model
- register project_status in admin
- add project_status endpoints
- add project_status seed data

### Why did you make the changes (we will use this info to test)?
N/A

2024-11-30 19:25 UTC, del9ra requested changes
Hi Denzel,
Thank you for working on this! I tested it, and everything worked well on my end. I just have a couple of questions:
1. Why are the descriptions on the 5th and 6th lines in quotation marks in the app/core/initial_data/PD_Table and Field Explanations - ProjectStatus - Data.csv file? Do you think this has an impact on how the code works?
2. Shouldn't the uuid field be mentioned in the _seed.py file?

2025-01-09 03:31 UTC, dmartin4820 commented
> Hi Denzel, Thank you for working on this! I tested it, and everything worked well on my end. I just have a couple of questions:
> 
>     1. Why are the descriptions on the 5th and 6th lines in quotation marks in the app/core/initial_data/PD_Table and Field Explanations - ProjectStatus - Data.csv file? Do you think this has an impact on how the code works?
> 
>     2. Shouldn't the uuid field be mentioned in the _seed.py file?

Hey Del, thanks for the comments.

1. I'm unsure how that got that way. The excel sheet doesn't have the quotes. I'll change that.
2. Good point. All the other seed files have UUID, but the [table in the excel sheet,](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit?gid=419535315#gid=419535315) for this PR, didn't have an id column

2025-02-06 19:15 UTC, fyliu commented
> 2. Good point. All the other seed files have UUID, but the [table in the Google sheet,](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit?gid=419535315#gid=419535315) for this PR, didn't have an UUID column. @Neecolaa @fyliu Can we make an update to[ the Project Status table in Google sheets](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit?gid=419535315#gid=419535315) so that it contains an id column? By doing this we would maintain consistency with the other tables and seed data with UUID fields.

I guess it depends on if we still need it set to specific values. The values it's being set to in the spreadsheet aren't really UUID values.

Originally, I let the database generate the ID/UUID values since it's an auto-generated field and the initial data sheets didn't have the values. Then @ethanstrominger said he needed to set the values for testing purposes, so we did that for some of the tables. But I don't think it's being used in tests right now?

We should bring this up at the meeting and ask if we still need to set this.

2025-02-19 21:04 UTC, del9ra approved these changes
Hi @dmartin4820 ,
Thanks for your contribution! Nice work on this, it looks great to me!

2025-02-20 23:37 UTC, fyliu requested changes
Thanks for working on this! I looked at this more closely and found a couple more things to improve.

2025-02-20 23:37 UTC, fyliu commented on app/core/models.py
> +    current_status_id = models.ForeignKey(
This should be `current_status`.

The old code was written before we realized Django convention is to drop the `_id` ending for foreign key relations.

2025-02-20 23:37 UTC, fyliu commented on app/core/initial_data/PD_ Table and field explanations - ProjectStatus - Data.csv
> +Deleted,Holds for 90 days before final removal (used for test project entries, or mistakes that do not need to be remembered)
Sorry, can you add back the double quotes?

I think the double quotes are actually necessary for the convert.py script to work. They're likely added by google to help any csv parser read it.

2025-02-27 06:31 UTC, dmartin4820 commented on app/core/initial_data/PD_ Table and field explanations - ProjectStatus - Data.csv
> +Deleted,Holds for 90 days before final removal (used for test project entries, or mistakes that do not need to be remembered)
Added back. It was definitely needed otherwise the csv parser would not run.

2025-02-27 23:27 UTC, fyliu requested changes
Thanks for making the changes. They look great!

I'm sorry, I just noticed another little thing.

The admin site adds an "s" at the end when displaying the plural form of the model. It doesn't know to use "project statuses". 
![2025-02-27 15 26 00 localhost 6b88d8307465](https://github.com/user-attachments/assets/b126cd5a-5b6e-43c6-af2c-585c93bb0b83)

In  `models.py` you can search for "verbose_name_plural" and use that as an example to add the plural for it. I think you should make it all lowercase and let Django deal with the capitalization. I see the existing code is doing something different.

2025-03-06 06:04 UTC, dmartin4820 commented
> Thanks for making the changes. They look great!
> 
> I'm sorry, I just noticed another little thing.
> 
> The admin site adds an "s" at the end when displaying the plural form of the model. It doesn't know to use "project statuses". ![2025-02-27 15 26 00 localhost 6b88d8307465](https://private-user-images.githubusercontent.com/1160105/417818249-b126cd5a-5b6e-43c6-af2c-585c93bb0b83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEyNDA4OTYsIm5iZiI6MTc0MTI0MDU5NiwicGF0aCI6Ii8xMTYwMTA1LzQxNzgxODI0OS1iMTI2Y2Q1YS01YjZlLTQzYzYtYWYyYy01ODVjOTNiYjBiODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMDZUMDU1NjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE2NGExNDhhMzcxN2EyMDQyNzk0ZjczYzM2ZTg3ZjZhZjRjMzYyZTg3ODc4NmZlODk3MzkxNjU2NTAzNDAxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zeRBuUfWCoyOOc-glBvEZ97gpkSryCrNd2x3zUDEbWk)
> 
> In `models.py` you can search for "verbose_name_plural" and use that as an example to add the plural for it. I think you should make it all lowercase and let Django deal with the capitalization. I see the existing code is doing something different.
I went and added the line for project status and checked that I could see the correct plural in the admin page:

![project_status_plural_change](https://github.com/user-attachments/assets/caa0cfad-0ce9-4363-9058-54e4a66ece18).

Don't know why my page is acting that way, but either way project status is plural as expected. Let me know if there's anything else. Thank you for the review and additions so far.

2025-03-06 23:24 UTC, fyliu approved these changes
Thanks. It looks great!

I'll combine the fixes into the original commits and merge them in.

2025-03-06 23:26 UTC, merged